velas/web-wallet

data-scheme.ls
pages/stake/accounts.ls
pages/validators.ls
staking-funcs.ls

https://velasnetwork.atlassian.net/browse/VLWA-1155
[VLWA-1155](https://velasnetwork.atlassian.net/browse/VLWA-1155) – [defect] bad gateway error after refreshing staking tab multiple times

Display fetch errors on validators screen VLWA-1155

---

package.json

[VLWA-1537](https://velasnetwork.atlassian.net/browse/VLWA-1537) – Native transaction from Transak is not displayed in tx history

version update VLWA-1537

---

package-lock.json
package.json

[VLWA-1529](https://velasnetwork.atlassian.net/browse/VLWA-1529) – Upgrade minimist to 1.2.6 version

upgrade isomorphic-fetch to 3.0.0 VLWA-1529

---

components/amount-fiat-field.ls
components/sliders/network-slider.ls
components/trx-custom-gas-price.ls
components/trx-fee.ls
pages/custom-token.ls
pages/send-contract.ls
pages/send.ls
pages/token-migration.ls
send-funcs.ls
web3.ls

[VLWA-1621](https://velasnetwork.atlassian.net/browse/VLWA-1621) – only internal EVM transactions are shown in history

retrurn s4end-fucns.ls VLWA-1621

---

.github/workflows/build-push-prod.yml
e2e/src/tests/stable/links.test.ts

[VLWA-1620](https://velasnetwork.atlassian.net/browse/VLWA-1620) – Run tests in parallel after prod deploy

VLWA-1620 run tests in parallel after prod deploy

---

package-lock.json
package.json
pages/staking2.ls
yarn.lock

[VLWA-1625](https://velasnetwork.atlassian.net/browse/VLWA-1625) – Update old version of staking.2.0 to @velas/staking.2.0

VLWA-1625 update staking module

---

pages/no_internet_banner.ls

[VLWA-1664](https://velasnetwork.atlassian.net/browse/VLWA-1664) – clean "no internet" messages from console

VLWA-1664 cleanup

---

package-lock.json
package.json
yarn.lock

[VLWA-1665](https://velasnetwork.atlassian.net/browse/VLWA-1665) – update staking2.0 to v.1.0.1

VLWA-1665-updated-staking2.0-to-v.1.0.2

---

pages/wallet-expanded.ls
pages/wallets-mobile.ls

[VLWA-1671](https://velasnetwork.atlassian.net/browse/VLWA-1671) – Add button buy to USDV

VLWA-1671 added button buy to USDV

---

.github/workflows/build-push-prod.yml
.github/workflows/e2e-tests.yml
e2e/src/api/axios-config.ts
e2e/src/api/explorers-api.ts
e2e/src/api/velas-testnet/axios-config.ts
e2e/src/tests/swap/swap.test.ts

[VLWA-1638](https://velasnetwork.atlassian.net/browse/VLWA-1638) – 6. Enable swap tests run after deploy to testnet (not on every PR)

VLWA-1638 Swap tests

---

install-plugin.ls
pages/wallet-expanded.ls
plugin-loader.ls

[VLWA-1677](https://velasnetwork.atlassian.net/browse/VLWA-1677) – make USDV default asset

Add usdv in default tokens array VLWA-1677

---

pages/history.ls
pages/locked.ls
refresh-txs.ls
transactions.ls

[VLWA-1661](https://velasnetwork.atlassian.net/browse/VLWA-1661) – Add retry button for failed tx history

render retry button in case failed txs history VLWA-1661 web3t

---

e2e/src/tests/swap/swap.test.ts

[VLWA-1713](https://velasnetwork.atlassian.net/browse/VLWA-1713) – set minimum amount for each swap in autotests

decrease min swap in tests usdc, usdt VLWA-1713

---

package.json

update `@velas/staking.2.0` version
[vlwa-1746](https://velasnetwork.atlassian.net/browse/vlwa-1746) – Validators BE unhandled error "Cannot read property 'rewards' of null"

vlwa-1746 update/staking-to-1-0-4-v?expand=1

---

e2e/package-lock.json
e2e/package.json
e2e/src/tests/stable/balance.test.ts

[VLWA-1788](https://velasnetwork.atlassian.net/browse/VLWA-1788) – handle 503 error at velasNative connection in staking test

VLWA-1788 update e2e package files

---

package-lock.json
package.json

[VLWA-1882](https://velasnetwork.atlassian.net/browse/VLWA-1882) – update staking 2.0 module && update package.json in wallet repo

VLWA-1882 updated staking module

---

package-lock.json

[VLWA-1819](https://velasnetwork.atlassian.net/browse/VLWA-1819) – web3t: wrong import module name

Staking v 1.1.1 VLWA-1819

---

package-lock.json
package.json

[VLWA-1946](https://velasnetwork.atlassian.net/browse/VLWA-1946) – tab nibbing vulnerability

VLWA-1946 updated staking module v.1.1.2

---

refresh-wallet.ls
transactions.ls

[VLWA-1945](https://velasnetwork.atlassian.net/browse/VLWA-1945) – refresh balance after tx sent

Balance update after tx sent VLWA-1945

---

package.json

[VLWA-2092](https://velasnetwork.atlassian.net/browse/VLWA-2092) – Update infura token for mainnet

udpate version VLWA-2092

---

e2e/src/tests/stable/transactions.test.ts
e2e/src/tests/stable/wallets.test.ts
e2e/src/tests/swap/custom-swap.test.ts
e2e/src/tests/swap/swap.test.ts
package-lock.json
package.json

[VLWA-1552](https://velasnetwork.atlassian.net/browse/VLWA-1552) – part of stake left on stake account after request withdraw with use max

VLWA-1552 updated @velas/staking.2.0 to v1.1.3

---

pages/stake/accounts.ls

[VLWA-2236](https://velasnetwork.atlassian.net/browse/VLWA-2236) – after new acount created 'withdraw' button is shown instead 'delegate' button

bugfix: VLWA-2236

---

pages/stake/account_details.ls

[VLWA-2240](https://velasnetwork.atlassian.net/browse/VLWA-2240) – cannot read properties of undefined error after balance update while on staking account details

reinit PublicKey and Secret key at velas-staking api VLWA-2240 web3t 

---

velas/velas-staking.js

[VLWA-2202](https://velasnetwork.atlassian.net/browse/VLWA-2202) – staking 1.0: add 'change authority' on stake account details page

fix missing stake account in getNextSeed method VLWA-2202

---

install-plugin.ls
pages/wallet-expanded.ls
pages/wallets-mobile.ls
plugin-loader.ls

[VLWA-2278](https://velasnetwork.atlassian.net/browse/VLWA-2278) – remove USDV web-wallet main screen

make usdv optional web3t VLWA-2278

---

e2e/playwright.config.ts
e2e/src/screens/staking-2.ts
e2e/src/screens/staking.ts
e2e/src/tests/staking/staking.test.ts
e2e/src/tests/staking/staking2.test.ts
package-lock.json

[VLWA-2648](https://velasnetwork.atlassian.net/browse/VLWA-2648) – e2e big amounts in staking (old wallet)

VLWA-2648 e2e tests staking with big amounts validation

---

package.json

[VLWA-2686](https://velasnetwork.atlassian.net/browse/VLWA-2686) – NEW Wallet staking 2.0: can't stake big amounts - more than 9,008,000

Staking2.0 VLWA-2686

---

package-lock.json

[VLWA-2720](https://velasnetwork.atlassian.net/browse/VLWA-2720) – big amounts staking for desktop wallet

lock updates VLWA-2720

---

pages/send.ls

[VLWA-2958](https://velasnetwork.atlassian.net/browse/VLWA-2958) – highlight bridge message in swap

make swap notification more visible VLWA-2958
